### ISSUE TITLE
Bug in the progress bar

### ISSUE THREAD

**Issue by tminussi** [tminussi/hacktoberfest-2018-checker#4]
Currently there's a bug in the progress bar. It auto completes even if users have not completed all 5 PR. (i.e, if the bar is at 40%, it shows as complete)

**Comment by meetcric** [comment]
i want to take this issue?

**Comment by tminussi** [comment]
please, go ahead @meetcric

**Comment by tminussi** [comment]
Fixed by @hovoodd on PR #10
