### ISSUE TITLE
Add support for i18n

### ISSUE THREAD

**Issue by tminussi** [tminussi/hacktoberfest-2018-checker#7]
Right now, all the messages sent back to the user are in EN-US.

Help improving this codebase by adding Internationalization to it.

**Comment by lucchmielowski** [comment]
Hi ! I would like to work on this ! :smiley:

**Comment by tminussi** [comment]
Feel free, @lucchmielowski !

Once you're done with this, I will add issues to support individual languages, so you'll also be able to contirbute with translations for your own language :)

**Comment by lucchmielowski** [comment]
Thanks @tminussi ! Quick question:  can I use [i18next](https://www.i18next.com/) to add internationalization ? :thinking:
